# Generated by Django 2.2.3 on 2019-09-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='operational_parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceId', models.CharField(max_length=60)),
                ('LocationId', models.IntegerField()),
                ('ShiftId', models.IntegerField()),
                ('Temp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Humidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TimeStamp', models.DateTimeField()),
                ('SensorId', models.CharField(max_length=60)),
            ],
        ),
    ]
