# Generated by Django 2.2.3 on 2019-09-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='operational_parameter',
            table='operationalparameter',
        ),
    ]
