# Generated by Django 2.2.3 on 2019-09-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_rest', '0002_auto_20190921_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='operational_parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPId', models.IntegerField()),
                ('DeviceId', models.CharField(max_length=60)),
                ('LocationId', models.IntegerField()),
                ('ShiftId', models.IntegerField()),
                ('Temp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Humidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TimeStamp', models.DateTimeField()),
                ('SensorId', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'operationalparameters',
            },
        ),
        migrations.RenameModel(
            old_name='operational_parameter',
            new_name='operational_parameter_dummy',
        ),
        migrations.AlterModelTable(
            name='operational_parameter_dummy',
            table='operationalparameterdummy',
        ),
    ]
