# Generated by Django 2.2.3 on 2019-09-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_rest', '0003_auto_20190921_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='operational_parameter_dummy',
        ),
    ]
